### ISSUE TITLE
Закодированные аудио

### ISSUE THREAD

**Issue by SyferOK** [vodka2/vk-audio-token#11]
Доброго времени суток, возникла такая проблема, раньше при использовании кода vk official получал список своих аудио с нормальным видом ссылок на mp3, теперь же они такие https://cs1-65v4.vkuseraudio.net/p18/c2b37b04f8f/f30851a0e61d4d/index.m3u8?extra=mKaYXiMlLR4Nau5Pp1Rtb29K1reUga0MzMNjoAQ1flY42A_0KHDjJ6hoTBUbPPpvIiSgWyHHJ2OhP0WYYiO2gd8pfOK50ZUQcTm36qvpqcQeyP7YnQVZhIUNG--iHasqZVicwPj8_Zy44e87NOgny0xN

как их можно расшифровать?

**Comment by SyferOK** [comment]
есть прямая ссылка этой же песни получена с m.vk.com - https://cs1-65v4.vkuseraudio.net/p18/f30851a0e61d4d.mp3?extra=mKaYXiMlLR4Nau5Pp1Rtb29K1reUga0MzMNjoAQ1flY42A_0KHDjJqdqTBUbPPpvIiSgWyHHJ2OhP0WYYiO2gd8pfOK50ZUQcTm36qvpqcQeyP7YnghchI8BF-6nHqUjalSfwPP_8JC47-lvM-d_n0kbvPk

видно что f30851a0e61d4d это название песни, и после ?extra= 113 символов одинаковы (mKaYXiMlLR4Nau5Pp1Rtb29K1reUga0MzMNjoAQ1flY42A_0KHDjJqdqTBUbPPpvIiSgWyHHJ2OhP0WYYiO2gd8pfOK50ZUQcTm36qvpqcQeyP7Yn) а вот как сгенирировать остальной код чтобы получить аудио?

**Comment by vodka2** [comment]
@SyferOK `extra` же не влияет, можно без этого параметра. То есть подойдёт такой код:
```php
   if(strpos($url, "/audios/")){
        echo preg_replace('~^(.+?)/[^/]+?/audios/([^/]+)/.+$~', '\\1/audios/\\2.mp3', $url);
    } else {
        echo preg_replace('~^(.+?)/(p[0-9]+)/[^/]+?/([^/]+)/.+$~', '\\1/\\2/\\3.mp3', $url);
    }
```
