### ISSUE TITLE
Привязка к IP

### ISSUE THREAD

**Issue by jus37** [vodka2/vk-audio-token#12]
Как известно, ссылки на музыку привязаны к IP юзера, который их запрашивал. Есть необходимость использовать эти ссылки на фронте, получая сами ссылки на бэкенде (соответсвенно IP фронта и бэка разные). Есть ли возможность каким то образом перекодировать ссылку для нужного IP?

**Comment by nokimaro** [comment]
Такой возможности нету.
Чтобы отдавать файлы пользователям, придётся прогонять их через свой сервер (проксировать).
