### ISSUE TITLE
content_restricted

### ISSUE THREAD

**Issue by jellyjus** [vodka2/vk-audio-token#14]
При запросе с серверов европы, некоторые треки отдаются без url и с ключем "content_restricted":
`     "id": 456239018,
                "owner_id": 539314228,
                "artist": "Artik & Asti",
                "title": "",
                "duration": 217,
                "date": 1554462845,
                "url": "",
                "is_hq": true,
                "track_genre_id": 14,
                "access_key": "692fa93bec77d87051",
                "content_restricted": 6
}`
С тем же access_key из РФ с теми же треками все ок. Пробовал получать access_key с машины в европе, результат тот же. Хотя из приложения Kate mobile c VPN треки работают. В чем может быть проблема? Спасибо

**Comment by vodka2** [comment]
Решил всё-таки воспроизвести, у меня некоторые треки Artik & Asti с зарубежных IP даже через Kate не работают, также  "content_restricted": 6.
