### ISSUE TITLE
Есть ли информация по лимитам при использовании таких токенов?

### ISSUE THREAD

**Issue by ugozhaev** [vodka2/vk-audio-token#16]
Добрый день. Вы не тестировали токены на лимиты? Какие есть ограничения при их использовании? По запросам в секунду, по запросам в сутки и т.п. В бан не отправляют аккаунты при активном использовании методов audio?

**Comment by vodka2** [comment]
@ugozhaev не тестировал на лимиты, насчёт ограничений знаю только то, что если получить несколько токенов на один аккаунт, то старые уже не работают. Часто использую токены на разных аккаунтах, ни один аккаунт пока не забанили, но я делаю не очень много запросов. Если получится протестировать на лимиты и есть возможность поделиться информацией, я могу добавить информацию в README.

**Comment by ugozhaev** [comment]
Спасибо, жаль здесь до лички не добраться )

**Comment by vodka2** [comment]
@ugozhaev есть аккаунт на habr.com — ImIeee и почта vodka2vodka на rambler.ru

**Comment by ugozhaev** [comment]
Добрый день. Внезапно, вк начал выдавать, что аудио api недоступен. Какие-то вводные для токенов сломались?

**Comment by vodka2** [comment]
@ugozhaev странно, только что попробовал получить токен и с его помощью аудиозаписи, всё работает. Когда именно появляется эта ошибка, можно более подробный сценарий?

**Comment by ugozhaev** [comment]
получаю токены как в microg
делаю запросы
запросы обычные нормально работают
запросы к аудио вызывают ошибку доступа - audio api is closed и все такое

**Comment by vodka2** [comment]
@ugozhaev может, проблема в неправильных запросах? Скрипт examples/usage/example_kate.php нормально работает с полученными токенами?

**Comment by ugozhaev** [comment]
Завтра напишу, как с кодом буду. Удобно?

**Comment by ugozhaev** [comment]
Извините за беспокойство. По какой-то причине слово User-Agent оказалось заменено на абракадабру.

**Comment by vodka2** [comment]
@ugozhaev ничего страшного, хорошо, что всё работает.

**Comment by ugozhaev** [comment]
Добрый день. Токены начали просить капчу. Код ошибки vk api 14. Сталкивались с такой проблемой?

**Comment by vodka2** [comment]
@ugozhaev Добрый день. Не сталкивался и опять не очень понятно. Что просит капчу — получение токена или использование токена? Если второе, то, может, из-за слишком частых запросов?

**Comment by ugozhaev** [comment]
Использование токена просит капчу. Скорее всего частых и очень многочисленных ) Жаль, что не сталкивались. Извините за беспокойство.
