### ISSUE TITLE
how get non secure access_token

### ISSUE THREAD

**Issue by umerov1999** [vodka2/vk-audio-token#20]
how get non secure access_token without &sig official token reciver?

**Comment by vodka2** [comment]
@umerov1999 please see the last commit in [temp-official-no-sig](https://github.com/vodka2/vk-audio-token/tree/temp-official-no-sig) branch. Does it work for you? I'll probably merge it on the weekend.

**Comment by umerov1999** [comment]
Not Work 
![image](https://user-images.githubusercontent.com/3888404/75282351-f4a76e80-5821-11ea-9e6a-4dcb61bbc0e2.png)

**Comment by vodka2** [comment]
@umerov1999 Please try example/vk_official.php and then example/usage/vk_official.php scripts first and post the errors here. If they produce no errors then the problem is your code. If you show the part of your code where you are obtaining and using tokens, I can probably tell what is wrong.

**Comment by umerov1999** [comment]
Работает, я просто не тот User-Agent выставил

**Comment by umerov1999** [comment]
VK_APIMETHOD Akkount(Token, VKAndroid_USERAGENT);
	Akkount["audio.get"] // << HTTP_PARAMS(
		//HParam("https", "1"),
		//HParam("device_id", device_id),
		//HParam("lang", "ru")
	//);
		;
	win_message().show((stringstream() << Akkount().Object).str());

Works too

**Comment by umerov1999** [comment]
Сделал модификацию вк феникса с поддержкой музыки и скачиванием 
![Screenshot_20200301-010959](https://user-images.githubusercontent.com/3888404/75615774-86ccb100-5b59-11ea-91fc-282d43cf513e.png)
