### ISSUE TITLE
Не понимаю многого...

### ISSUE THREAD

**Issue by turnedwrong** [vodka2/vk-audio-token#22]
Здравствуйте. Я понемногу пишу библиотеку для 100% доступа ко всем методам user api vk. Реализовал почти все методы. Камнем преткновения для меня стало получение refreshed token. Дело в том, что пишу я на python и никак не могу освоить php. Возможно вы подскажите мне как получить receipt именно на python. Буду вам очень признателен

**Comment by vodka2** [comment]
@turnedwrong Добрый день. Что именно не ясно? В общем, для получения receipt нужно получить GMS ID и токен, отправить MTalk запрос, потом уже непосредственно делать запросы для регистрации. Есть также [версия кода на C++](https://github.com/vodka2/vk-music-fs/blob/master/src/token/TokenReceiver.cpp#L29), [на C#](https://github.com/artemshuba/meridian/pull/47) , если эти языки более понятны. В целом, я cам думаю портировать код получения токена на Python.

**Comment by LulzLoL231** [comment]
> В целом, я cам думаю портировать код получения токена на Python.

Здравствуйте, ещё не передумали делать интерпретацию на Python?

**Comment by vodka2** [comment]
@LulzLoL231 Добрый день. Если честно, немного забыл про то, что хотел так сделать. Сейчас есть время, можно в принципе попробовать. Или вы это написали к тому, что уже сами всё сделали? 
Интересно, что [на Github](https://github.com/search?q=966882ba564c2619d55d0a9afd4327a38c327456&type=Code) есть несколько репозиториев с кодом получения токена, но в версии [на Python](https://github.com/MrDandycorn/vk-botting/blob/44aa4f40b5fd6161bc438e4eb3a4cf5efd837463/vk_botting/auth.py) вроде как GMS ID и токен захардкожены.

**Comment by LulzLoL231** [comment]
@vodka2 Я думал сделать, но я пока не понимаю как это работает, а вы уже знакомы с технологией, а раз вы хотели сделать интерпретацию на Python, т.к. вы уже знакомы с технологией, мне кажется у вас лучше получится написать чем у меня.

**Comment by vodka2** [comment]
@LulzLoL231 https://github.com/vodka2/vkaudiotoken-python , по крайней мере у меня работает.
