### ISSUE TITLE
Cannot get audios from walls

### ISSUE THREAD

**Issue by frozencodeuz** [vodka2/vk-audio-token#23]
Hi vodka2.
Good job!!!
I cannot get list of audios from from walls(communities) I tried with ID of group but it doesn't give any data. But it's working for my own userID
**I tried with `wall.get` but it's not giving all audios list**
![image](https://user-images.githubusercontent.com/52082114/78926257-39c3ef00-7ab6-11ea-8323-faabdc68c26b.png)
![image](https://user-images.githubusercontent.com/52082114/78926275-40526680-7ab6-11ea-91b1-dd6c2391ad3f.png)

**Comment by vodka2** [comment]
@frozencodeuz Community ids start with minus symbol. So try 
```php
$ownerId = -39832528;
...
```

**Comment by frozencodeuz** [comment]
Worked thanks!!!
