### ISSUE TITLE
Аудио недоступны

### ISSUE THREAD

**Issue by Arsen-chechen** [vodka2/vk-audio-token#26]
Успешно получаю токен, но при попытке вызвать, например, метод audio.get возвращает только одно аудио -  https://vk.com/mp3/audio_api_unavailable.mp3
Пробовал даже сделать свои gms credentials, ошибка не исчезает.
код:
> $ curl "https://api.vk.com/method/audio.get?v=5.116&access_token=MYTOKEN"

>{"response":{"count":1,"items":[{"id":1,"owner_id":100,"artist":"и в официальных приложениях ВКонтакте","title":"Аудио доступно на vk.com","duration":25,"date":1481906888,"url":"https:\/\/vk.com\/mp3\/audio_api_unavailable.mp3"}]}

gms получал через android-эмулятор memu.

**Comment by vodka2** [comment]
@Arsen-chechen как минимум нужно указать User-Agent. В [примерах использования](https://github.com/vodka2/vk-audio-token/tree/master/src/examples/usage) токена он указан.

**Comment by Arsen-chechen** [comment]
> @Arsen-chechen как минимум нужно указать User-Agent. В [примерах использования](https://github.com/vodka2/vk-audio-token/tree/master/src/examples/usage) токена он указан.

Да, заработало с user-agent'ом kate mobile, благодарю.
