### ISSUE TITLE
Доступны не все аудио

### ISSUE THREAD

**Issue by kozyaba** [vodka2/vk-audio-token#28]
Добрый день!

Заметил, что api возвращает массив аудио, но далеко не везде есть URL на mp3, хотя в официальных клиентах и Kate аудио доступны. Использую авторизацию и user-agent Kate mobile. Проблема наблюдается со всеми методами.  
Это проблема со стороны вк или я как-то неправильно обращаюсь? Есть ли решение?

![image](https://user-images.githubusercontent.com/11595903/83506714-30f90380-a4d0-11ea-8b73-3db1567dd581.png)

**Comment by celsoft** [comment]
Здесь две причины.
1. гео блок.
2. доступ только по подписке.

В первом случае достаточно работать с ru ip.

**Comment by kozyaba** [comment]
> Здесь две причины.
> 
> 1. гео блок.
> 2. доступ только по подписке.
> 
> В первом случае достаточно работать с ru ip.

Похоже у меня первый вариант) Сервер не в РФ
Спасибо за ответ!
