### ISSUE TITLE
does not display the token

### ISSUE THREAD

**Issue by KPACAB4UK** [vodka2/vk-audio-token#3]
Getting new android checkin auth data...

Receiving token...
PHP Notice:  Undefined property: stdClass::$error_description in C:\vk-audio-token-master\src\Vodka2\VKAudioToken\TokenException.php on line 18
PHP Fatal error:  Uncaught Vodka2\VKAudioToken\TokenException: Can't obtain token. Error description: Unknown error in C:\vk-audio-token-master\src\Vodka2\VKAudioToken\TokenReceiver.php:38
Stack trace:
#0 C:\vk-audio-token-master\src\Vodka2\VKAudioToken\TokenReceiver.php(22): Vodka2\VKAudioToken\TokenReceiver->getNonRefreshed()
#1 C:\vk-audio-token-master\src\cli\vk-audio-token.php(142): Vodka2\VKAudioToken\TokenReceiver->getToken()
#2 {main}
  thrown in C:\vk-audio-token-master\src\Vodka2\VKAudioToken\TokenReceiver.php on line 38

**Comment by vodka2** [comment]
@KPACAB4UK It seems that VK has (temporarily) banned your account. Try changing the code in one of the examples:

```
...
try {
    echo $receiver->getToken();
} catch(TokenException $e){
    var_dump($e->extra);
}
```
After that the script should print the response that was returned from VK server.

**Comment by KPACAB4UK** [comment]
@vodka2 No, the account is not banned. On the way there was a captcha. thx
