### ISSUE TITLE
Обновить код в composer

### ISSUE THREAD

**Issue by arys777** [vodka2/vk-audio-token#31]
В composer стоит старый код

**Comment by vodka2** [comment]
@arys777 Сейчас версия в Composer отличается только на один коммит с кодом. Думаю, на днях доделаю новую функциональность и небольшой рефакторинг, чтобы были более существенные изменения для новой версии. Как временное решение — использовать dev-master.

**Comment by vodka2** [comment]
@arys777 Выложил новую версию: улучшения в коде и в документации. Хотя насчёт «на днях» я, конечно, погорячился.

**Comment by arys777** [comment]
@vodka2 спасибо!
