### ISSUE TITLE
кириллица

### ISSUE THREAD

**Issue by Kucklovod00** [vodka2/vk-audio-token#37]
здравствуйте. не выдает запросы с кириллицей. 

запрос:
```
$query = "ЛАУД";

curl_setopt(
    $ch,
    CURLOPT_URL,
    "https://api.vk.com/method/audio.search?access_token=".TOKEN.
    "&q=".urlencode($query)."&performer_only=0&count=10&v=5.95"
);
```
выдает случайные результаты, которые вообще не подходят под запрос

**Comment by vodka2** [comment]
@Kucklovod00 не могу воспроизвести ошибку с вашим кодом. У меня находит треки «ЛАУД feat. Thomas Mraz», «ЛАУД feat. Cream Soda» и т.п. Токен получил только что с помощью `example_microg.php`. Может быть проблема в нём, или в IP?

**Comment by Kucklovod00** [comment]
проблема была на моей стороне, не заметил что включилась кодировка win-1251, в место utf-8.
спасибо за отзывчивость!
