### ISSUE TITLE
e: Token was not refreshed, tokens are the same

### ISSUE THREAD

**Issue by alashow** [vodka2/vk-audio-token#4]
Hey,

Do you know why tokens don't refresh? Is it because of the fixed check-in token?
`Uncaught Vodka2\TokenException: Token was not refreshed, tokens are the same in`

**Comment by vodka2** [comment]
@alashow It seems so. I've tried using GMS credentials that were obtained a long ago using droidguard string, and got the same error. Not sure about the microG checkin. I don't think it is a serious problem, because you can always obtain new credentials, but I'll mention it in the README.
