### ISSUE TITLE
токен

### ISSUE THREAD

**Issue by vitaliy1379** [vodka2/vk-audio-token#5]
Здравствуйте, у вас работает скрипт ? не могу получить токен

**Comment by vodka2** [comment]
@vitaliy1379 `src/cli/vk-audio-token.php -m login pass` или `example_microg.php login pass`

**Comment by vitaliy1379** [comment]
-m vk-audio-token.php
![default](https://user-images.githubusercontent.com/25883726/46577959-259fbd00-c9fb-11e8-90ee-40f2e714305a.PNG)

**Comment by vodka2** [comment]
@vitaliy1379 проблема в настройках PHP, сейчас посмотрю, как можно это исправить.

**Comment by vodka2** [comment]
@vitaliy1379 Уберите точку с запятой в строке `;extension=openssl` в php.ini.

**Comment by vitaliy1379** [comment]
спасибо,заработало
