### ISSUE TITLE
через оф.вк

### ISSUE THREAD

**Issue by vitaliy1379** [vodka2/vk-audio-token#6]
Здравствуйте, подскажите какая команда если не через кейт мобайл ,а через оф. вк(example_vkofficial)

**Comment by vodka2** [comment]
@vitaliy1379 Запустите `C:\php\php.exe src/examples/example_vkofficial.php login pass` и скрипт выведет данные, необходимые для запросов к API.  Примеры запросов — в файле `examples/usage/example_vkofficial.php`

**Comment by vitaliy1379** [comment]
PHP Warning:  include(../autoloader.php): failed to open stream: No such file or directory in C:\vk-audio-token\src\examples\example_vkofficial.php on line 3
PHP Warning:  include(): Failed opening '../autoloader.php' for inclusion (include_path='.;C:\php\pear') in C:\vk-audio-token\src\examples\example_vkofficial.php on line 3
PHP Fatal error:  Uncaught Error: Class 'Vodka2\VKAudioToken\CommonParams' not found in C:\vk-audio-token\src\examples\example_vkofficial.php:12
Stack trace:
#0 {main}
  thrown in C:\vk-audio-token\src\examples\example_vkofficial.php on line 12

**Comment by vodka2** [comment]
@vitaliy1379 загрузите версию кода из последнего коммита или перед выполнением скрипта перейдите в его каталог: `cd  C:\vk-audio-token\src\examples`

**Comment by vitaliy1379** [comment]
cd C:\vk-audio-token\src\examples а после ввести команду какую команду 
если же просто C:\vk-audio-token\src\examples\example_vkofficial.php то открывает данный файл редактором

**Comment by vodka2** [comment]
@vitaliy1379 после того, как перешли в каталог (`cd C:\vk-audio-token\src\examples`), выполните `c:\php\php.exe example_vkofficial.php login pass`.  Вообще я же написал, можно загрузить последнюю версию и запустить скрипт, как я предложил в [предыдущем комментарии.](https://github.com/vodka2/vk-audio-token/issues/6#issuecomment-431020545)

**Comment by vitaliy1379** [comment]
PHP Fatal error:  Uncaught Vodka2\VKAudioToken\TokenException: Can't obtain token. Error extra: NULL in C:\src\Vodka2\VKAudioToken\TokenReceiverOfficial.php:40
Stack trace:
#0 C:\src\Vodka2\VKAudioToken\TokenReceiverOfficial.php(21): Vodka2\VKAudioToken\TokenReceiverOfficial->getNonRefreshed()
#1 C:\src\examples\example_vkofficial.php(17): Vodka2\VKAudioToken\TokenReceiverOfficial->getToken()
#2 {main}
  thrown in C:\src\Vodka2\VKAudioToken\TokenReceiverOfficial.php on line 40

**Comment by vitaliy1379** [comment]
делал как вы писали с новым скриптом так и через каталог

**Comment by vodka2** [comment]
@vitaliy1379 проблема опять в настройках PHP и Windows. Загрузите файл `cacert.pem` с [сайта curl](https://curl.haxx.se/docs/caextract.html), скопируйте его в `c:\php`. Далее, найдите в `c:\php\php.ini` строку `;curl.cainfo = ` и замените её на `curl.cainfo=c:\php\cacert.pem`.

**Comment by vitaliy1379** [comment]
спасибо заработало
