### ISSUE TITLE
Problem with the tokens

### ISSUE THREAD

**Issue by uglyDev** [vodka2/vk-audio-token#7]
Hi vodka2,

at first, great work :-)

i've used your script "vk-audio-token.php" to gather a vk audio api token.
When i use this token to query the vk audio api, the api reply with an error code:
```
"error_code": 25,
"error_msg": "Token confirmation required",
```

I don't passed an gms_id and gms_token to the script. I've seen in your code both will be generated by the class AndroidCheckin if they are not passed to the script. 

Do you have any idea why this happens?

**Comment by vodka2** [comment]
@uglyDev Could you be more specific? How are you using  `vk-audio-token.php` script, have you tried specifiyng the `-m` option? How are you querying the vk audio API? There are some [examples](https://github.com/vodka2/vk-audio-token/tree/master/src/examples/usage) in the examples/usage directory, I've just tried `example_kate.php` with a newly obtained token and it works. You may also try gathering a token and querying API using another VK account and IP.

**Comment by vasea101** [comment]
Hello , can anyone make a video instruction how to install & use this script ?

**Comment by vodka2** [comment]
@vasea101 isn't the [installation](https://github.com/vodka2/vk-audio-token#installation) section of the README enough? What is not clear there?

**Comment by vasea101** [comment]
I found out , thx much for this script.

**Comment by blackarcanis** [comment]
Hi @vodka2, a good job is done here!
However, we have noticed this same error:
`"error_code": 25,
"error_msg": "Token confirmation required"`

Only for some user VK accounts and not for others. Even if we are using correctly the complete authentication flow, it's working for 90% of VK accounts I think but for some others, the "audio." methods are not working and still returning this error.
Any idea maybe?
