### ISSUE TITLE
Проблема при запуске файла vk-audio-token.php

### ISSUE THREAD

**Issue by aloe47** [vodka2/vk-audio-token#9]
>> php src/cli/vk-audio-token.php -m log pass

PHP Fatal error:  Uncaught Error: Call to undefined function Vodka2\VKAudioToken\curl_init() in /root/vk-audio-tokens/src/Vodka2/VKAudioToken/CommonParams.php:27
Stack trace:
#0 /root/vk-audio-tokens/src/cli/vk-audio-token.php(114): Vodka2\VKAudioToken\CommonParams->__construct()
#1 {main}
  thrown in /root/vk-audio-tokens/src/Vodka2/VKAudioToken/CommonParams.php on line 27

**Comment by aloe47** [comment]
Исправил ошибку, но API audio.search все равно не вызывается, как быть?

**Comment by vodka2** [comment]
`Call to undefined function Vodka2\VKAudioToken\curl_init()`

Нужно, чтобы в PHP была поддержка curl.

**Comment by pasha00000** [comment]
В Ubuntu мне помогла установка php-curl
